[workspace]
members = [
    "day-eight",
    "day-five",
    "day-four",
    "day-nine",
    "day-one",
    "day-seven",
    "day-six",
    "day-three",
    "day-two",
]
resolver = "3"

[workspace.package]
version = "0.1.0"

[workspace.dependencies.clap]
version = "4.5"
features = ["derive"]
