[workspace]
members = [
    "day-four",
    "day-one",
    "day-three",
    "day-two",
]
resolver = "3"

[workspace.package]
version = "0.1.0"

[workspace.dependencies.clap]
version = "4.5"
features = ["derive"]
