[package]
name = "day-nine"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
geo = "0.32.0"
geo-types = "0.7.18"

